MyChicken/Controllers/OrderController.cs
using MyChicken.Models;
using MyChicken.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyChicken.Services;
using log4net;
using System.Globalization;

namespace MyChicken.Controllers
{
    [Authorize]
    public class OrderController : BaseController
    {
        ApplicationDbContext db = new ApplicationDbContext();
        OrderService os = new OrderService();
        ProductService ps = new ProductService();
        //
        // GET: /Order/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var model = new OrderViewModel { DeliveryDate = DateTime.Today.AddDays(1) };
            try
            {
                List<Product> products = db.Products.Where(x=>x.IsArchived==false).ToList();
                foreach ( var p in products)
                {
                    model.Products.Add(new OrderProductViewModel { Product = p, Amount=0, Quantity=0 });
                }
                Trace("Order page showed",TraceLevel.Debug);
            }
            catch (Exception ex)
            {
                Trace("Order page show error",TraceLevel.Fatal, ex);
            }
            return View(model);
        }

        // Post: /Order/
        [HttpPost]
        public ActionResult Index(OrderViewModel orderVM, FormCollection form)
        {
            
            Trace("Begin new order saving", TraceLevel.Debug);
            //Construction of product list
            var tabIndex = form["products_Index"].Split(',');
            var lop = new List<OrderProduct>();
            foreach(var elt in tabIndex)
            {
                var strId = form[string.Format("products_{0}_Id",elt)];
                long Id = long.Parse(strId);
                var Qte = int.Parse(form[string.Format("products_{0}_Quantity", elt)]);
                var product = ps.GetbyId(Id);
                var op = new OrderProduct()
                {
                    //Product = product,
                    ProductID = product.Id,
                    Number = Qte,
                    QtyAmount = product.Amount * Qte
                };
                lop.Add(op);
            }

            var model = os.CreateOrder(lop, User.Identity.Name, orderVM.DeliveryDate);
            //os.Add(model);

            Trace("End order saving", TraceLevel.Debug);
            TempData["order"] = model;
            return RedirectToAction("summary");
        }



        public ActionResult Summary()
        {
            var order = new Order();
            var data = (Order)TempData["order"];
            order = data != null ? data : order;
            return View(order);
        }
 
        // GET: /Order/MyList
        public ActionResult MyList()
        {
            try
            {
                OrderService os = new OrderService();
                var cdes = os.GetMyList(User.Identity.Name).Take(10);
                Trace("User last ten order showed", TraceLevel.Info);
                return View(cdes);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex);
                return View();
            }
        }
        
        [Authorize(Roles="Admin,superviseur")]
        public ActionResult List(string username, string deliverydate)
        {
             OrderService os = new OrderService();
             var cdes = os.GetAll();
             if (!string.IsNullOrEmpty(username))
                 cdes = cdes.Where(x => x.User.UserName == username).ToList();
             if (!string.IsNullOrEmpty(deliverydate))
             {
                 DateTime dt;
                 if (DateTime.TryParseExact(deliverydate, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out dt))
                 {
                     cdes = cdes.Where(x => x.DeliveryDate >= dt).ToList();
                 }
             }
             Trace("All users order showed", TraceLevel.Info);
             return View(cdes);            
        }

        // GET: /Order/Delete/5
        [Authorize(Roles = "Admin,superviseur")]
        public ActionResult Operation(long id, string op)
        {
            var model = db.Orders.FirstOrDefault(x => x.Id == id);
            ViewData["op"] = op;
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,superviseur")]
        public ActionResult Operation(long id, string op, string comment)
        {
            OrderService os = new OrderService();
            var model = db.Orders.FirstOrDefault(x => x.Id == id);
            var a = ViewData["op"];
            switch(op)
            { 
                case "annuler" :
                    os.MajStatut(id, comment, Statut.ANNULE);
                    break;
                case "valider" :
                    os.MajStatut(id, comment, Statut.VALIDE);
                    break;
                case "livrer":
                    os.MajStatut(id, comment, Statut.LIVRE);
                    break;
                case "supprimer" :
                    os.Delete(id);
                    break;
                default : 
                    break;
            }
            Trace("Order "+id+" statut updated : " + op , TraceLevel.Info);
            return RedirectToAction("List");
        }


    }
}

MyChicken/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyChicken.Models;
using MyChicken.Services;
using AutoMapper;
using MyChicken.ViewModel;

namespace MyChicken.Controllers
{
    [Authorize(Roles="Admin")]
    public class ProductController : BaseController
    {
        ProductService ps = new ProductService();

        // GET: /Product/
        public ActionResult Index()
        {
            var data = ps.GetAll();
            List<ProductViewModel> model = new List<ProductViewModel>();
            data.ForEach(x=>model.Add(Tools.Mapping<Product, ProductViewModel>.DefautMapping(x)));
            return View(model);
        }

        // GET: /Product/Details/5
        public ActionResult Details(long id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = ps.GetbyId(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: /Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Product/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,Image,Amount,IsArchived")] ProductViewModel product)
        {
            //var config = new MapperConfiguration(cfg => cfg.CreateMap<ProductViewModel, Product>());
            //var mapper = config.CreateMapper();
            //Product model = mapper.Map<Product>(product);
            var model = Tools.Mapping<ProductViewModel, Product>.DefautMapping(product);

            if (ModelState.IsValid)
            {
                ps.Add(model);
                Trace("New product created : " + product.Name, TraceLevel.Info);
                return RedirectToAction("Index");
            }

            return View(product);
        }



        // GET: /Product/Edit/5
        public ActionResult Edit(long id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = ps.GetbyId(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /Product/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Image,Amount,IsArchived")] Product product)
        {
            if (ModelState.IsValid)
            {
                ps.Update(product);
                Trace("Product updated : " + product.Name, TraceLevel.Info);
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: /Product/Delete/5
        public ActionResult Delete(long id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = ps.GetbyId(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            ps.Delete(id);
            Trace("Product deleted : " + id, TraceLevel.Info);
            return RedirectToAction("Index");
        }
    }
}

MyChicken/Views/Shared/FileNotFound.cshtml
@{
    ViewBag.Title = "FileNotFound";
}

<h2>FileNotFound</h2>

<div class="error">
    La page demandée n'existe pas ou plus.
    Rendez vous à la page d'accueil @Html.ActionLink("ici","index","order")
</div>

MyChicken/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SaveurEnOr</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SaveurEnOr", "Index", "Order", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Order")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Mes commandes", "MyList", "Order")</li>
                    }
                    @if (User.IsInRole("Admin") || User.IsInRole("Superviseur"))
                    {
                        <li>@Html.ActionLink("Commandes", "List", "Order")</li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Produits","Index","Product")</li>
                                <li>@Html.ActionLink("Superviseur", "ManageSupervisor", "Admin")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Saveurs en or</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MyChicken/Views/Shared/_OrderPartial.cshtml
@using MyChicken.Models
@using System.Collections.Generic
@model ICollection<OrderProduct>
<div>
    <table class="table table-striped">
        <caption>Details de la commande</caption>
        <thead>
            <tr>
                <th>Produit</th>
                <th>Quantité</th>
                <th>Montant</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Product.Name
                    </td>                    
                    <td>
                        @item.Number
                    </td>
                    <td>@item.QtyAmount</td>
                </tr>
            }
        </tbody>
    </table>
</div>